# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Installing Gstreamer 1.0
      run: |
        sudo apt-get update && \
        sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -yq \
          jackd \
          gcc \
          git \
          ca-certificates \
          libgl1-mesa-dev xorg-dev \
          libunwind-dev \
          libgstreamer1.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools \
          gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 \
          gstreamer1.0-pulseaudio

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        make citest
